ouster/os_sensor:
  ros__parameters:
    sensor_hostname: ''
    udp_dest: ''
    mtp_dest: ''
    mtp_main: false
    lidar_mode: ''
    timestamp_mode: ''
    udp_profile_lidar: ''
    metadata: ''
    lidar_port: 0
    imu_port: 0
ouster/os_cloud:
  ros__parameters:
    sensor_frame: ''    # Frame of physical sensor
    lidar_frame: ''     # Frame of lidar scans
    imu_frame: ''       # Frame of IMU data
    timestamp_mode: ''
